pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/saadmann18/calculatoro.git'
            }
        }
        stage('Build') {
            steps {
                sh 'g++ -o calculator calculator.cpp'
            }
        }
        stage('Test') {
            steps {
                sh './calculator'
            }
        }
    }
    post {
        success {
            echo 'Build and test successful!'
        }
        failure {
            echo 'Build or test failed. Check the logs.'
        }
    }
}
