pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/saadmann18/calculatoro.git'
            }
        }
        stage('Build') {
            steps {
                bat 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe" Calculatoro.sln /p:Configuration=Release'
            }
        }
        stage('Test') {
            steps {
                bat '"C:\\Users\\Saad\\source\\repos\\Calculatoro\\Debug\\Calculatoro.exe"'
            }
        }
    }
    post {
        success {
            echo 'Build and test successful!'
        }
        failure {
            echo 'Build or test failed. Check the logs.'
        }
    }
}
